services:
  random-sentences:
    container_name: random-sentence-service
    build:
      context: ./sentences 
      dockerfile: Dockerfile
    env_file: ./sentences/.env
    ports:
      - 8080:8080
    networks:
      - main

  activemq:
    image: apache/activemq-classic:5.18.3
    container_name: activemq
    ports:
      - "50061:61616"
      - "50062:61613"
      - "8161:8161"
    env_file:
      ./environment/.env
    networks:
      - main

networks:
  main:
